### PR TITLE
Attempted fix for "unexpected cancel" issue in #34

### LINKED ISSUE #34: `TaskGroup` propagates `CancelledError` rather than a `MultiError` on exception
See the following snippet:
```py
import asyncio
import aiotools

async def error():
    await asyncio.sleep(1)
    raise Exception("bad stuff")

async def main():
    try:
        async with aiotools.TaskGroup() as tg:
            tg.create_task(error())
            await asyncio.sleep(5)
    except Exception as e:
        print(f"Got inner {repr(e)}")
        raise

try:
    asyncio.run(main())
except BaseException as e:
    print(f"Got outer {repr(e)}")
```

```
Got outer CancelledError()
```

Is this expected behavior?  It feels wrong, since a) it ate an exception and b) the task wasn't actually cancelled.

This is Python 3.9 and aiotools 1.4.0.

### PR DESCRIPTION
**Pull request by bdowning**
This attempts to fix #34 .  I'm not quite sure what the intended logic behind the `base_error` stuff was, and as such I'm not sure if I've messed something up here.  But the tests pass!  :)

### CODE REVIEW

**Comment by bdowning** [comment]
@achimnol Here's another one, though I'd appreciate a careful look at my solution to ensure I haven't broken something unintentionally (though all tests pass!)

**Comment by achimnol** [comment]
I think this would be better reviewed by the original authors of the module, @1st1 and @elprans.
As you may know, our `taskgroup` module is imported from [EdgeDB's `_taskgroup` module](https://github.com/edgedb/edgedb-python/blob/master/edgedb/_taskgroup.py).

Note that Python 3.11 will introduce the concept of `ExceptionGroup` with a new syntax `except*:`.  `aiotools` currently targets Python 3.6, but I'm considering migration of `taskgroup` and `ptaskgroup` modules to Python 3.11 once it gets released, while keeping other modules (`aiotools.context`, ...) compatible with Python 3.6.

**Comment by bdowning** [comment]
That does sound really nice (was unaware of that PEP), though because a lot of us will be stuck on older Pythons for quite a while (Lambda is a good example, it's still on 3.9 unless you roll your own runtime) having a compatibility mode would be great.

**Comment by achimnol** [comment]
> That does sound really nice (was unaware of that PEP), though because a lot of us will be stuck on older Pythons for quite a while (Lambda is a good example, it's still on 3.9 unless you roll your own runtime) having a compatibility mode would be great.

I'm not sure yet how Python 3.11 organize the TaskGroup API in the stdlib asyncio (which is the main motivation of ExceptionGroup), but if it turns out good, we could leave the current aiotools' implementation as an alternative option for old Python users.

At that time, we could bump the version of aiotools to 2.0 and drop backward-compatilibility to Python 3.6 and 3.7, as 3.6 is already EOL and 3.7 would become EOL in June the next year, while 3.11 is expected to be released on October this year.

**Comment by achimnol** [comment]
Also take a look at python/cpython#31270!

**Comment by bdowning** [comment]
That's awesome, I've lost count of how many times I've shot myself in the foot due to dangling tasks.  Having this in stdlib should help a lot.

**Comment by achimnol** [comment]
I think the problem is `_is_base_error()` implementation.
Updated it to use the same logic from Python 3.11's `asyncio.TaskGroup._is_base_error()`.

**Comment by bdowning** [comment]
:+1:  LGTM

I can confirm that just the `_is_base_error` patch fixes the "expected cancel" errors I was seeing in my actual codebase.

**Pull request merged**
